services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./polyboquette_db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      POSTGRES_DB: ${DB_NAME:-polyboquette_db}
      POSTGRES_USER: ${DB_USER:-polyboquette_db_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-do0J1tpYrvQUkLMFmqxgegUjIZRcB3ha}

  web:
    build: ./app
    command: gunicorn --chdir /app server:app --bind 0.0.0.0:5000
    # ON SUPPRIME LE VOLUME ./app:/app ICI
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-polyboquette_db_user}:${DB_PASSWORD:-do0J1tpYrvQUkLMFmqxgegUjIZRcB3ha}@db:5432/${DB_NAME:-polyboquette_db}
      - SECRET_KEY=${SECRET_KEY:-une_cle_secrete_temporaire_par_defaut}
    depends_on:
      - db

volumes:
  postgres_data: